# Generated by Django 3.2.7 on 2021-09-30 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YourCurrentTradelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='You Do Not Have Any Current TradeLines', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('tradeline_age', models.CharField(max_length=100)),
                ('tradeline_date', models.DateField()),
                ('tradeline_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YourBusinessRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='You Do Not Have Any Current Recommendations', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateYourCompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_address', models.CharField(max_length=100)),
                ('anual_sales', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('employees', models.CharField(max_length=100)),
                ('line_of_business', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SendestaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('maximum_credit_recommendation', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=100)),
                ('reason_of_dispute', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendesta_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('anual_sales', models.CharField(max_length=100)),
                ('business_form', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('employees', models.CharField(max_length=100)),
                ('date_incorporated', models.DateTimeField(auto_now=True)),
                ('age', models.CharField(max_length=100)),
                ('state_incorporated', models.CharField(max_length=100)),
                ('name_of_principle', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('judgements', models.CharField(max_length=100)),
                ('liens', models.CharField(max_length=100)),
                ('suits', models.CharField(max_length=100)),
                ('ucc_filings', models.CharField(max_length=100)),
                ('special_events', models.CharField(max_length=100)),
                ('company_events', models.CharField(max_length=100)),
                ('profit_and_loss', models.CharField(max_length=100)),
                ('total_number_of_enquiries', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('report', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
