# Generated by Django 3.2.7 on 2021-10-02 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendestaScore',
            new_name='VudokeBusinessIntelligenceScore',
        ),
        migrations.RenameField(
            model_name='companyinformation',
            old_name='sendesta_number',
            new_name='vukode_number',
        ),
    ]
